# Generated by Django 4.2.3 on 2023-07-06 04:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Назва принтеру"),
                ),
                ("point_id", models.IntegerField(verbose_name="ID точки")),
                (
                    "api_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Ключ доступу до API"
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=7,
                        verbose_name="Тип чеку",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("kitchen", "Kitchen"), ("client", "Client")],
                        max_length=7,
                        verbose_name="Тип чеку",
                    ),
                ),
                ("order", models.JSONField(verbose_name="Замовлення")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("rendered", "Rendered"),
                            ("printed", "Printed"),
                        ],
                        default="new",
                        max_length=8,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "pdf_generate_in_progress",
                    models.BooleanField(default=False, verbose_name="В процесі"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="pdf/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["pdf"], message="Приймаються лише PDF-файли."
                            )
                        ],
                        verbose_name="Файл чеку",
                    ),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.printer"
                    ),
                ),
            ],
        ),
    ]
